### ISSUE TITLE
example of send sms does not compile

### ISSUE THREAD

**Issue by rfaass** [centaq/arduino-async-sms#1]
I expected the example to just compile but it did not. It seems difficult to find a piece of code that does not need to be debugged first.

**Comment by centaq** [comment]
Thanks, done

**Comment by rfaass** [comment]
C:\Users\Robert Faass\AppData\Local\Temp\.arduinoIDE-unsaved20221125-8984-1griywv.dgjt\sketch_dec25b\sketch_dec25b.ino:3:35: error: call of overloaded 'AsyncSMS(HardwareSerial*, long int)' is ambiguous
 AsyncSMS smsHelper(&Serial3, 57600);
                                   ^
In file included from C:\Users\Robert Faass\AppData\Local\Temp\.arduinoIDE-unsaved20221125-8984-1griywv.dgjt\sketch_dec25b\sketch_dec25b.ino:1:0:
c:\Users\Robert Faass\Documents\Arduino\libraries\AsyncSMS\src/AsyncSMS.h:116:2: note: candidate: AsyncSMS::AsyncSMS(HardwareSerial*, uint32_t)
  AsyncSMS(HardwareSerial *gsm, uint32_t baudRate) : AsyncSMS(gsm, baudRate, false) { }
  ^~~~~~~~
c:\Users\Robert Faass\Documents\Arduino\libraries\AsyncSMS\src/AsyncSMS.h:115:2: note: candidate: AsyncSMS::AsyncSMS(HardwareSerial*, bool)
  AsyncSMS(HardwareSerial *gsm, bool autoStateRefresh) : AsyncSMS(gsm, 0, autoStateRefresh) { }
  ^~~~~~~~
C:\Users\Robert Faass\AppData\Local\Temp\.arduinoIDE-unsaved20221125-8984-1griywv.dgjt\sketch_dec25b\sketch_dec25b.ino: In function 'void setup()':
C:\Users\Robert Faass\AppData\Local\Temp\.arduinoIDE-unsaved20221125-8984-1griywv.dgjt\sketch_dec25b\sketch_dec25b.ino:7:84: warning: ISO C++ forbids converting a string constant to 'char*' [-Wwrite-strings]
   smsHelper.send("+48123456789", "This is my Arduino driven SMS module working", 45);
                                                                                    ^

exit status 1

Compilation error: call of overloaded 'AsyncSMS(HardwareSerial*, long int)' is ambiguous

When I compile example send sms

**Comment by rfaass** [comment]
Every example runs into: Compilation error: call of overloaded 'AsyncSMS(HardwareSerial*, long int)' is ambiguous

**Comment by centaq** [comment]
Yes, I know. I've corrected that yesterday and released the 1.1.2 version.

Please update your package and check after that.
Thanks

wt., 27 gru 2022 o 02:55 rfaass ***@***.***> napisał(a):

**Comment by rfaass** [comment]
Thank you, how do I install the library? It does not appear in the library manager as 1.1.2... I manually copied over the files in the library directory for this package but that does not work:

c:\Users\Robert Faass\Documents\Arduino\libraries\AsyncSMS\src\AsyncSMS.cpp: In member function 'void AsyncSMS::process()':
c:\Users\Robert Faass\Documents\Arduino\libraries\AsyncSMS\src\AsyncSMS.cpp:93:46: warning: ISO C++ forbids converting a string constant to 'char*' [-Wwrite-strings]
    log("RECEIVED MESSAGE MAX LENGTH EXCEEDED");
                                              ^
c:\Users\Robert Faass\Documents\Arduino\libraries\AsyncSMS\src\src\AsyncSMS.cpp: In member function 'void AsyncSMS::process()':
c:\Users\Robert Faass\Documents\Arduino\libraries\AsyncSMS\src\src\AsyncSMS.cpp:93:46: warning: ISO C++ forbids converting a string constant to 'char*' [-Wwrite-strings]
    log("RECEIVED MESSAGE MAX LENGTH EXCEEDED");
                                              ^
c:\Users\Robert Faass\Documents\Arduino\libraries\AsyncSMS\src\src\AsyncSMS.cpp:122:22: warning: ISO C++ forbids converting a string constant to 'char*' [-Wwrite-strings]
    log("SMS received");
                      ^
c:\Users\Robert Faass\Documents\Arduino\libraries\AsyncSMS\src\AsyncSMS.cpp:122:22: warning: ISO C++ forbids converting a string constant to 'char*' [-Wwrite-strings]
    log("SMS received");
                      ^
c:\Users\Robert Faass\Documents\Arduino\libraries\AsyncSMS\src\src\AsyncSMS.cpp:130:37: warning: ISO C++ forbids converting a string constant to 'char*' [-Wwrite-strings]
   log("Waiting for Response Timeout");
                                     ^
c:\Users\Robert Faass\Documents\Arduino\libraries\AsyncSMS\src\AsyncSMS.cpp:130:37: warning: ISO C++ forbids converting a string constant to 'char*' [-Wwrite-strings]
   log("Waiting for Response Timeout");
                                     ^
c:\Users\Robert Faass\Documents\Arduino\libraries\AsyncSMS\src\src\AsyncSMS.cpp: In member function 'void AsyncSMS::processSMSSending()':
c:\Users\Robert Faass\Documents\Arduino\libraries\AsyncSMS\src\src\AsyncSMS.cpp:151:21: warning: ISO C++ forbids converting a string constant to 'char*' [-Wwrite-strings]
    log("Sending SMS");
                     ^
c:\Users\Robert Faass\Documents\Arduino\libraries\AsyncSMS\src\AsyncSMS.cpp: In member function 'void AsyncSMS::processSMSSending()':
c:\Users\Robert Faass\Documents\Arduino\libraries\AsyncSMS\src\AsyncSMS.cpp:151:21: warning: ISO C++ forbids converting a string constant to 'char*' [-Wwrite-strings]
    log("Sending SMS");
                     ^
c:\Users\Robert Faass\Documents\Arduino\libraries\AsyncSMS\src\AsyncSMS.cpp: In member function 'void AsyncSMS::handleCommandResponse()':
c:\Users\Robert Faass\Documents\Arduino\libraries\AsyncSMS\src\AsyncSMS.cpp:191:13: warning: ISO C++ forbids converting a string constant to 'char*' [-Wwrite-strings]
   log("OK--");
             ^
c:\Users\Robert Faass\Documents\Arduino\libraries\AsyncSMS\src\src\AsyncSMS.cpp: In member function 'void AsyncSMS::handleCommandResponse()':
c:\Users\Robert Faass\Documents\Arduino\libraries\AsyncSMS\src\src\AsyncSMS.cpp:191:13: warning: ISO C++ forbids converting a string constant to 'char*' [-Wwrite-strings]
   log("OK--");
             ^
c:\Users\Robert Faass\Documents\Arduino\libraries\AsyncSMS\src\src\AsyncSMS.cpp:193:16: warning: ISO C++ forbids converting a string constant to 'char*' [-Wwrite-strings]
   log("ERROR--");
                ^
c:\Users\Robert Faass\Documents\Arduino\libraries\AsyncSMS\src\src\AsyncSMS.cpp:195:19: warning: ISO C++ forbids converting a string constant to 'char*' [-Wwrite-strings]
   log("SMS SEND--");
                   ^
c:\Users\Robert Faass\Documents\Arduino\libraries\AsyncSMS\src\AsyncSMS.cpp:193:16: warning: ISO C++ forbids converting a string constant to 'char*' [-Wwrite-strings]
   log("ERROR--");
                ^
c:\Users\Robert Faass\Documents\Arduino\libraries\AsyncSMS\src\AsyncSMS.cpp:195:19: warning: ISO C++ forbids converting a string constant to 'char*' [-Wwrite-strings]
   log("SMS SEND--");
                   ^
c:\Users\Robert Faass\Documents\Arduino\libraries\AsyncSMS\src\AsyncSMS.cpp:197:13: warning: ISO C++ forbids converting a string constant to 'char*' [-Wwrite-strings]
   log("CREG");
             ^
c:\Users\Robert Faass\Documents\Arduino\libraries\AsyncSMS\src\src\AsyncSMS.cpp:197:13: warning: ISO C++ forbids converting a string constant to 'char*' [-Wwrite-strings]
   log("CREG");
             ^
c:\Users\Robert Faass\Documents\Arduino\libraries\AsyncSMS\src\AsyncSMS.cpp:203:12: warning: ISO C++ forbids converting a string constant to 'char*' [-Wwrite-strings]
   log("CSQ");
            ^
c:\Users\Robert Faass\Documents\Arduino\libraries\AsyncSMS\src\src\AsyncSMS.cpp:203:12: warning: ISO C++ forbids converting a string constant to 'char*' [-Wwrite-strings]
   log("CSQ");
            ^
c:\Users\Robert Faass\Documents\Arduino\libraries\AsyncSMS\src\AsyncSMS.cpp:209:17: warning: ISO C++ forbids converting a string constant to 'char*' [-Wwrite-strings]
   log("NIEZNNAE");
                 ^
c:\Users\Robert Faass\Documents\Arduino\libraries\AsyncSMS\src\src\AsyncSMS.cpp:209:17: warning: ISO C++ forbids converting a string constant to 'char*' [-Wwrite-strings]
   log("NIEZNNAE");
                 ^
c:\Users\Robert Faass\Documents\Arduino\libraries\AsyncSMS\src\src\AsyncSMS.cpp: In member function 'void AsyncSMS::log(String)':
c:\Users\Robert Faass\Documents\Arduino\libraries\AsyncSMS\src\src\AsyncSMS.cpp:382:19: warning: invalid conversion from 'const char*' to 'char*' [-fpermissive]
   logger(msg.c_str());
          ~~~~~~~~~^~
c:\Users\Robert Faass\Documents\Arduino\libraries\AsyncSMS\src\AsyncSMS.cpp: In member function 'void AsyncSMS::log(String)':
c:\Users\Robert Faass\Documents\Arduino\libraries\AsyncSMS\src\AsyncSMS.cpp:382:19: warning: invalid conversion from 'const char*' to 'char*' [-fpermissive]
   logger(msg.c_str());
          ~~~~~~~~~^~
C:\Users\Robert Faass\AppData\Local\Temp\arduino-sketch-41B35CE7A1E485AC4800873335CE26D9\libraries\AsyncSMS\src\AsyncSMS.cpp.o (symbol from plugin): In function `AsyncSMS::AsyncSMS(Stream*, unsigned long, bool, bool)':
(.text+0x0): multiple definition of `AsyncSMS::AsyncSMS(Stream*, unsigned long, bool, bool)'
C:\Users\Robert Faass\AppData\Local\Temp\arduino-sketch-41B35CE7A1E485AC4800873335CE26D9\libraries\AsyncSMS\AsyncSMS.cpp.o (symbol from plugin):(.text+0x0): first defined here
C:\Users\Robert Faass\AppData\Local\Temp\arduino-sketch-41B35CE7A1E485AC4800873335CE26D9\libraries\AsyncSMS\src\AsyncSMS.cpp.o (symbol from plugin): In function `AsyncSMS::AsyncSMS(Stream*, unsigned long, bool, bool)':
(.text+0x0): multiple definition of `AsyncSMS::AsyncSMS(Stream*, unsigned long, bool, bool)'
C:\Users\Robert Faass\AppData\Local\Temp\arduino-sketch-41B35CE7A1E485AC4800873335CE26D9\libraries\AsyncSMS\AsyncSMS.cpp.o (symbol from plugin):(.text+0x0): first defined here
C:\Users\Robert Faass\AppData\Local\Temp\arduino-sketch-41B35CE7A1E485AC4800873335CE26D9\libraries\AsyncSMS\src\AsyncSMS.cpp.o (symbol from plugin): In function `AsyncSMS::AsyncSMS(Stream*, unsigned long, bool, bool)':
(.text+0x0): multiple definition of `AsyncSMS::parseResultValues(String)'
C:\Users\Robert Faass\AppData\Local\Temp\arduino-sketch-41B35CE7A1E485AC4800873335CE26D9\libraries\AsyncSMS\AsyncSMS.cpp.o (symbol from plugin):(.text+0x0): first defined here
C:\Users\Robert Faass\AppData\Local\Temp\arduino-sketch-41B35CE7A1E485AC4800873335CE26D9\libraries\AsyncSMS\src\AsyncSMS.cpp.o (symbol from plugin): In function `AsyncSMS::AsyncSMS(Stream*, unsigned long, bool, bool)':
(.text+0x0): multiple definition of `AsyncSMS::enqueueWithoutNewLine(String)'
C:\Users\Robert Faass\AppData\Local\Temp\arduino-sketch-41B35CE7A1E485AC4800873335CE26D9\libraries\AsyncSMS\AsyncSMS.cpp.o (symbol from plugin):(.text+0x0): first defined here
C:\Users\Robert Faass\AppData\Local\Temp\arduino-sketch-41B35CE7A1E485AC4800873335CE26D9\libraries\AsyncSMS\src\AsyncSMS.cpp.o (symbol from plugin): In function `AsyncSMS::AsyncSMS(Stream*, unsigned long, bool, bool)':
(.text+0x0): multiple definition of `AsyncSMS::send(String, char*, unsigned char)'
C:\Users\Robert Faass\AppData\Local\Temp\arduino-sketch-41B35CE7A1E485AC4800873335CE26D9\libraries\AsyncSMS\AsyncSMS.cpp.o (symbol from plugin):(.text+0x0): first defined here
C:\Users\Robert Faass\AppData\Local\Temp\arduino-sketch-41B35CE7A1E485AC4800873335CE26D9\libraries\AsyncSMS\src\AsyncSMS.cpp.o (symbol from plugin): In function `AsyncSMS::AsyncSMS(Stream*, unsigned long, bool, bool)':
(.text+0x0): multiple definition of `AsyncSMS::retrySMSSend()'
C:\Users\Robert Faass\AppData\Local\Temp\arduino-sketch-41B35CE7A1E485AC4800873335CE26D9\libraries\AsyncSMS\AsyncSMS.cpp.o (symbol from plugin):(.text+0x0): first defined here
C:\Users\Robert Faass\AppData\Local\Temp\arduino-sketch-41B35CE7A1E485AC4800873335CE26D9\libraries\AsyncSMS\src\AsyncSMS.cpp.o (symbol from plugin): In function `AsyncSMS::AsyncSMS(Stream*, unsigned long, bool, bool)':
(.text+0x0): multiple definition of `AsyncSMS::enqueue(String)'
C:\Users\Robert Faass\AppData\Local\Temp\arduino-sketch-41B35CE7A1E485AC4800873335CE26D9\libraries\AsyncSMS\AsyncSMS.cpp.o (symbol from plugin):(.text+0x0): first defined here
C:\Users\Robert Faass\AppData\Local\Temp\arduino-sketch-41B35CE7A1E485AC4800873335CE26D9\libraries\AsyncSMS\src\AsyncSMS.cpp.o (symbol from plugin): In function `AsyncSMS::AsyncSMS(Stream*, unsigned long, bool, bool)':
(.text+0x0): multiple definition of `AsyncSMS::reinitGSMModuleConnection()'
C:\Users\Robert Faass\AppData\Local\Temp\arduino-sketch-41B35CE7A1E485AC4800873335CE26D9\libraries\AsyncSMS\AsyncSMS.cpp.o (symbol from plugin):(.text+0x0): first defined here
C:\Users\Robert Faass\AppData\Local\Temp\arduino-sketch-41B35CE7A1E485AC4800873335CE26D9\libraries\AsyncSMS\src\AsyncSMS.cpp.o (symbol from plugin): In function `AsyncSMS::AsyncSMS(Stream*, unsigned long, bool, bool)':
(.text+0x0): multiple definition of `AsyncSMS::init()'
C:\Users\Robert Faass\AppData\Local\Temp\arduino-sketch-41B35CE7A1E485AC4800873335CE26D9\libraries\AsyncSMS\AsyncSMS.cpp.o (symbol from plugin):(.text+0x0): first defined here
C:\Users\Robert Faass\AppData\Local\Temp\arduino-sketch-41B35CE7A1E485AC4800873335CE26D9\libraries\AsyncSMS\src\AsyncSMS.cpp.o (symbol from plugin): In function `AsyncSMS::AsyncSMS(Stream*, unsigned long, bool, bool)':
(.text+0x0): multiple definition of `AsyncSMS::checkRegistrationState(unsigned char, unsigned char)'
C:\Users\Robert Faass\AppData\Local\Temp\arduino-sketch-41B35CE7A1E485AC4800873335CE26D9\libraries\AsyncSMS\AsyncSMS.cpp.o (symbol from plugin):(.text+0x0): first defined here
C:\Users\Robert Faass\AppData\Local\Temp\arduino-sketch-41B35CE7A1E485AC4800873335CE26D9\libraries\AsyncSMS\src\AsyncSMS.cpp.o (symbol from plugin): In function `AsyncSMS::AsyncSMS(Stream*, unsigned long, bool, bool)':
(.text+0x0): multiple definition of `AsyncSMS::deleteAllSMS()'
C:\Users\Robert Faass\AppData\Local\Temp\arduino-sketch-41B35CE7A1E485AC4800873335CE26D9\libraries\AsyncSMS\AsyncSMS.cpp.o (symbol from plugin):(.text+0x0): first defined here
C:\Users\Robert Faass\AppData\Local\Temp\arduino-sketch-41B35CE7A1E485AC4800873335CE26D9\libraries\AsyncSMS\src\AsyncSMS.cpp.o (symbol from plugin): In function `AsyncSMS::AsyncSMS(Stream*, unsigned long, bool, bool)':
(.text+0x0): multiple definition of `AsyncSMS::dequeue()'
C:\Users\Robert Faass\AppData\Local\Temp\arduino-sketch-41B35CE7A1E485AC4800873335CE26D9\libraries\AsyncSMS\AsyncSMS.cpp.o (symbol from plugin):(.text+0x0): first defined here
C:\Users\Robert Faass\AppData\Local\Temp\arduino-sketch-41B35CE7A1E485AC4800873335CE26D9\libraries\AsyncSMS\src\AsyncSMS.cpp.o (symbol from plugin): In function `AsyncSMS::AsyncSMS(Stream*, unsigned long, bool, bool)':
(.text+0x0): multiple definition of `AsyncSMS::queueAvailable()'
C:\Users\Robert Faass\AppData\Local\Temp\arduino-sketch-41B35CE7A1E485AC4800873335CE26D9\libraries\AsyncSMS\AsyncSMS.cpp.o (symbol from plugin):(.text+0x0): first defined here
C:\Users\Robert Faass\AppData\Local\Temp\arduino-sketch-41B35CE7A1E485AC4800873335CE26D9\libraries\AsyncSMS\src\AsyncSMS.cpp.o (symbol from plugin): In function `AsyncSMS::AsyncSMS(Stream*, unsigned long, bool, bool)':
(.text+0x0): multiple definition of `AsyncSMS::clearSMSBuffer()'
C:\Users\Robert Faass\AppData\Local\Temp\arduino-sketch-41B35CE7A1E485AC4800873335CE26D9\libraries\AsyncSMS\AsyncSMS.cpp.o (symbol from plugin):(.text+0x0): first defined here
C:\Users\Robert Faass\AppData\Local\Temp\arduino-sketch-41B35CE7A1E485AC4800873335CE26D9\libraries\AsyncSMS\src\AsyncSMS.cpp.o (symbol from plugin): In function `AsyncSMS::AsyncSMS(Stream*, unsigned long, bool, bool)':
(.text+0x0): multiple definition of `AsyncSMS::parseSMS()'
C:\Users\Robert Faass\AppData\Local\Temp\arduino-sketch-41B35CE7A1E485AC4800873335CE26D9\libraries\AsyncSMS\AsyncSMS.cpp.o (symbol from plugin):(.text+0x0): first defined here
C:\Users\Robert Faass\AppData\Local\Temp\arduino-sketch-41B35CE7A1E485AC4800873335CE26D9\libraries\AsyncSMS\src\AsyncSMS.cpp.o (symbol from plugin): In function `AsyncSMS::AsyncSMS(Stream*, unsigned long, bool, bool)':
(.text+0x0): multiple definition of `AsyncSMS::log(char*)'
C:\Users\Robert Faass\AppData\Local\Temp\arduino-sketch-41B35CE7A1E485AC4800873335CE26D9\libraries\AsyncSMS\AsyncSMS.cpp.o (symbol from plugin):(.text+0x0): first defined here
C:\Users\Robert Faass\AppData\Local\Temp\arduino-sketch-41B35CE7A1E485AC4800873335CE26D9\libraries\AsyncSMS\src\AsyncSMS.cpp.o (symbol from plugin): In function `AsyncSMS::AsyncSMS(Stream*, unsigned long, bool, bool)':
(.text+0x0): multiple definition of `AsyncSMS::log(String)'
C:\Users\Robert Faass\AppData\Local\Temp\arduino-sketch-41B35CE7A1E485AC4800873335CE26D9\libraries\AsyncSMS\AsyncSMS.cpp.o (symbol from plugin):(.text+0x0): first defined here
C:\Users\Robert Faass\AppData\Local\Temp\arduino-sketch-41B35CE7A1E485AC4800873335CE26D9\libraries\AsyncSMS\src\AsyncSMS.cpp.o (symbol from plugin): In function `AsyncSMS::AsyncSMS(Stream*, unsigned long, bool, bool)':
(.text+0x0): multiple definition of `AsyncSMS::fillState(unsigned char, unsigned char*)'
C:\Users\Robert Faass\AppData\Local\Temp\arduino-sketch-41B35CE7A1E485AC4800873335CE26D9\libraries\AsyncSMS\AsyncSMS.cpp.o (symbol from plugin):(.text+0x0): first defined here
C:\Users\Robert Faass\AppData\Local\Temp\arduino-sketch-41B35CE7A1E485AC4800873335CE26D9\libraries\AsyncSMS\src\AsyncSMS.cpp.o (symbol from plugin): In function `AsyncSMS::AsyncSMS(Stream*, unsigned long, bool, bool)':
(.text+0x0): multiple definition of `AsyncSMS::findLineBreak(char*, unsigned int)'
C:\Users\Robert Faass\AppData\Local\Temp\arduino-sketch-41B35CE7A1E485AC4800873335CE26D9\libraries\AsyncSMS\AsyncSMS.cpp.o (symbol from plugin):(.text+0x0): first defined here
C:\Users\Robert Faass\AppData\Local\Temp\arduino-sketch-41B35CE7A1E485AC4800873335CE26D9\libraries\AsyncSMS\src\AsyncSMS.cpp.o (symbol from plugin): In function `AsyncSMS::AsyncSMS(Stream*, unsigned long, bool, bool)':
(.text+0x0): multiple definition of `AsyncSMS::checkFunctionResult(String)'
C:\Users\Robert Faass\AppData\Local\Temp\arduino-sketch-41B35CE7A1E485AC4800873335CE26D9\libraries\AsyncSMS\AsyncSMS.cpp.o (symbol from plugin):(.text+0x0): first defined here
C:\Users\Robert Faass\AppData\Local\Temp\arduino-sketch-41B35CE7A1E485AC4800873335CE26D9\libraries\AsyncSMS\src\AsyncSMS.cpp.o (symbol from plugin): In function `AsyncSMS::AsyncSMS(Stream*, unsigned long, bool, bool)':
(.text+0x0): multiple definition of `AsyncSMS::isNewSMS()'
C:\Users\Robert Faass\AppData\Local\Temp\arduino-sketch-41B35CE7A1E485AC4800873335CE26D9\libraries\AsyncSMS\AsyncSMS.cpp.o (symbol from plugin):(.text+0x0): first defined here
C:\Users\Robert Faass\AppData\Local\Temp\arduino-sketch-41B35CE7A1E485AC4800873335CE26D9\libraries\AsyncSMS\src\AsyncSMS.cpp.o (symbol from plugin): In function `AsyncSMS::AsyncSMS(Stream*, unsigned long, bool, bool)':
(.text+0x0): multiple definition of `AsyncSMS::isSMSSend()'
C:\Users\Robert Faass\AppData\Local\Temp\arduino-sketch-41B35CE7A1E485AC4800873335CE26D9\libraries\AsyncSMS\AsyncSMS.cpp.o (symbol from plugin):(.text+0x0): first defined here
C:\Users\Robert Faass\AppData\Local\Temp\arduino-sketch-41B35CE7A1E485AC4800873335CE26D9\libraries\AsyncSMS\src\AsyncSMS.cpp.o (symbol from plugin): In function `AsyncSMS::AsyncSMS(Stream*, unsigned long, bool, bool)':
(.text+0x0): multiple definition of `AsyncSMS::isOK()'
C:\Users\Robert Faass\AppData\Local\Temp\arduino-sketch-41B35CE7A1E485AC4800873335CE26D9\libraries\AsyncSMS\AsyncSMS.cpp.o (symbol from plugin):(.text+0x0): first defined here
C:\Users\Robert Faass\AppData\Local\Temp\arduino-sketch-41B35CE7A1E485AC4800873335CE26D9\libraries\AsyncSMS\src\AsyncSMS.cpp.o (symbol from plugin): In function `AsyncSMS::AsyncSMS(Stream*, unsigned long, bool, bool)':
(.text+0x0): multiple definition of `AsyncSMS::processSMSSending()'
C:\Users\Robert Faass\AppData\Local\Temp\arduino-sketch-41B35CE7A1E485AC4800873335CE26D9\libraries\AsyncSMS\AsyncSMS.cpp.o (symbol from plugin):(.text+0x0): first defined here
C:\Users\Robert Faass\AppData\Local\Temp\arduino-sketch-41B35CE7A1E485AC4800873335CE26D9\libraries\AsyncSMS\src\AsyncSMS.cpp.o (symbol from plugin): In function `AsyncSMS::AsyncSMS(Stream*, unsigned long, bool, bool)':
(.text+0x0): multiple definition of `AsyncSMS::isError()'
C:\Users\Robert Faass\AppData\Local\Temp\arduino-sketch-41B35CE7A1E485AC4800873335CE26D9\libraries\AsyncSMS\AsyncSMS.cpp.o (symbol from plugin):(.text+0x0): first defined here
C:\Users\Robert Faass\AppData\Local\Temp\arduino-sketch-41B35CE7A1E485AC4800873335CE26D9\libraries\AsyncSMS\src\AsyncSMS.cpp.o (symbol from plugin): In function `AsyncSMS::AsyncSMS(Stream*, unsigned long, bool, bool)':
(.text+0x0): multiple definition of `AsyncSMS::getResultParameter(String)'
C:\Users\Robert Faass\AppData\Local\Temp\arduino-sketch-41B35CE7A1E485AC4800873335CE26D9\libraries\AsyncSMS\AsyncSMS.cpp.o (symbol from plugin):(.text+0x0): first defined here
C:\Users\Robert Faass\AppData\Local\Temp\arduino-sketch-41B35CE7A1E485AC4800873335CE26D9\libraries\AsyncSMS\src\AsyncSMS.cpp.o (symbol from plugin): In function `AsyncSMS::AsyncSMS(Stream*, unsigned long, bool, bool)':
(.text+0x0): multiple definition of `AsyncSMS::handleCommandResponse()'
C:\Users\Robert Faass\AppData\Local\Temp\arduino-sketch-41B35CE7A1E485AC4800873335CE26D9\libraries\AsyncSMS\AsyncSMS.cpp.o (symbol from plugin):(.text+0x0): first defined here
C:\Users\Robert Faass\AppData\Local\Temp\arduino-sketch-41B35CE7A1E485AC4800873335CE26D9\libraries\AsyncSMS\src\AsyncSMS.cpp.o (symbol from plugin): In function `AsyncSMS::AsyncSMS(Stream*, unsigned long, bool, bool)':
(.text+0x0): multiple definition of `AsyncSMS::process()'
C:\Users\Robert Faass\AppData\Local\Temp\arduino-sketch-41B35CE7A1E485AC4800873335CE26D9\libraries\AsyncSMS\AsyncSMS.cpp.o (symbol from plugin):(.text+0x0): first defined here
collect2.exe: error: ld returned 1 exit status

exit status 1

Compilation error: exit status 1

**Comment by centaq** [comment]
Manually copying it in is a pretty bad idea, as you can see.

Open Arduino, go to Libraries Manager (Ctrl Shift I) then enter "Asyncsms"
in search text box.
In library row, select new version and install it

wt., 27 gru 2022 o 17:22 rfaass ***@***.***> napisał(a):

**Comment by rfaass** [comment]
Ahhh, that is what I tried but did not show up dear friend.
It might take a while to propagate?
Best regards, Robert
 

    On Tuesday, December 27, 2022 at 12:30:33 PM PST, centaq ***@***.***> wrote:  
 
 

Manually copying it in is a pretty bad idea, as you can see.

Open Arduino, go to Libraries Manager (Ctrl Shift I) then enter "Asyncsms"
in search text box.
In library row, select new version and install it

wt., 27 gru 2022 o 17:22 rfaass ***@***.***> napisał(a):

**Comment by rfaass** [comment]
Attached are my results with 1.1.2 as screenshots.
I am convinced a lot of know how went into this library and I appreciate it. I am not on your level, therefore I cannot debug this.
Thanks again.
Best regards, Robert
 

    On Tuesday, December 27, 2022 at 08:05:04 PM PST, Robert ***@***.***> wrote:  
 
 Ahhh, that is what I tried but did not show up dear friend.
It might take a while to propagate?
Best regards, Robert
 

    On Tuesday, December 27, 2022 at 12:30:33 PM PST, centaq ***@***.***> wrote:  
 
 

Manually copying it in is a pretty bad idea, as you can see.

Open Arduino, go to Libraries Manager (Ctrl Shift I) then enter "Asyncsms"
in search text box.
In library row, select new version and install it

wt., 27 gru 2022 o 17:22 rfaass ***@***.***> napisał(a):

**Comment by centaq** [comment]
Hi, don't know about what screenshot you are writing about. There is nothing pin to this post.

Is there another issue you have spotted ?

**Comment by rfaass** [comment]
mmmmh, only a warning here is the warning when  compiling:
C:\Users\Robert Faass\AppData\Local\Temp\.arduinoIDE-unsaved20221127-16116-1b4idyu.iuk9h\sketch_dec27a\sketch_dec27a.ino: In function 'void loop()':C:\Users\Robert Faass\AppData\Local\Temp\.arduinoIDE-unsaved20221127-16116-1b4idyu.iuk9h\sketch_dec27a\sketch_dec27a.ino:27:86: warning: ISO C++ forbids converting a string constant to 'char*' [-Wwrite-strings]     smsHelper.send("+48123456789", "This is my Arduino driven SMS module working", 45);                                                                                      ^Sketch uses 7910 bytes (3%) of program storage space. Maximum is 253952 bytes.Global variables use 1771 bytes (21%) of dynamic memory, leaving 6421 bytes for local variables. Maximum is 8192 bytes.

Thank you for the library, now gonna use it!

Best regards, Robert
 

    On Thursday, December 29, 2022 at 12:55:24 PM PST, centaq ***@***.***> wrote:  
 
 


Hi, don't know about what screenshot you are writing about. There is nothing pin to this post.

Is there another issue you have spotted ?

**Comment by centaq** [comment]
Thank you for this information.

I had compiler warnings turned off in my environment for some reason.

I've created a new release. It should propagate to Arduino libraries repo
probably in a couple of hours.

pt., 30 gru 2022 o 00:41 rfaass ***@***.***> napisał(a):

**Comment by rfaass** [comment]
Great thank you! 

Sent from Yahoo Mail on Android 
 
  On Mon, Jan 2, 2023 at 1:20 PM, ***@***.***> wrote:   

Thank you for this information.

I had compiler warnings turned off in my environment for some reason.

I've created a new release. It should propagate to Arduino libraries repo
probably in a couple of hours.

pt., 30 gru 2022 o 00:41 rfaass ***@***.***> napisał(a):
